#docker build -f Dockerfile-native -t docker-native:1.2 .
FROM rust:1.70-slim-bullseye as build

COPY Cargo.toml .
COPY Cargo.lock .
COPY src src

RUN apt-get update && apt-get install -y pkg-config libssl-dev

RUN cargo build --release

FROM debian:bullseye-slim

COPY --from=build /target/release/wasm-native native

ENTRYPOINT [ "/native" ]
