#docker build -f Dockerfile-native -t docker-native:1.1 .
FROM rust:1.70-slim-bullseye as build

COPY Cargo.toml .
COPY Cargo.lock .
COPY src src

RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --release

FROM scratch

COPY --from=build /target/release/wasm-native native

ENTRYPOINT [ "/native" ]
